### ISSUE TITLE
Improve Refresh of Map Icons for Furniture with Issues

### ISSUE THREAD

**Issue by Timothy-D** [exeGesIS-SDM/CAMS-Mobile#23] opened 2018-10-19 11:43 UTC
Currently when you sign off the issue on a furniture item on the app, the map icon for that furniture doesn't lose it's /!\ decoration until you have sync'd the data, processed it into CAMS and then re-sync'd. Can the icon update happen when the record is saved?

**Comment by LaineS** [comment] 2020-12-10 09:08
Note: See IssueCtrl.js line 452

**Comment by LaineS** [comment] 2020-12-10 12:18
The furniture map feature is now updated when each issue is saved and should show the resolved/unresolved issues correctly with the small yellow icon.

**Comment by am-esdm** [comment] 2020-12-10 16:02
**CAMS Mobile version:** v4.4.10
**Sync account:** xgWCP
**Tablet:** Samsung Galaxy Tab A
**Android version:** v5.1.1

**Result:**
Fail: The furniture's issue decoration is successfully removed when you initially save the record after updating the issue to resolved, but then if you view the issue form from the furniture again (and don't change anything in the issue record), then cancel back to the map, the issue decoration reappears for the now-resolved issue - it should stay removed

**Comment by Timothy-D** [comment] 2020-12-11 10:48
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.10
**Sync Account**: xgWCP
**Status**: Fail
**Details**: Confirming findings above:

1. Find Furniture item with issue on the map. Map icon shows with /!\ decoration. OK
2. View furniture details. Set condition = satisfactory.
3. View issue details from furniture form. Set status = resolved, set done date = now.
4. Save issue & return to map. Furniture map icon shows without decoration. OK
5. View furniture details and go to issue details. Don't change anything
6. Cancel issue form, returning to the map.
7. Furniture Map icon shows with /!\ decoration. NG
8. View furniture details and go to issue details. Don't change anything
9. Save issue form, returning to the map.
10. Furniture map icon shows without decoration. OK

So, if you return to the resolved issue and then cancel it, it seems to erroneously reset the map icon (can't tell if this is setting the HasIssues flag wrongly).

**Comment by LaineS** [comment] 2020-12-14 09:16
Fixed in v4.4.11

1. Sync data and find a furniture item with an unresolved issue on it
2. Open the furniture form, notice the Issue is listed at the bottom
3. Open the issue form, change the status to Resolved, save the form
4. Notice the furniture map icon now doesn't have the ! triangle on it
5. Re-open the furniture form, the issue is not listed. Save or Cancel and the map icon is refreshed correctly (i.e. without the ! triangle)

**Comment by Timothy-D** [comment] 2020-12-14 16:24
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.11
**Sync Account**: xgWCP
**Status**: Pass with associated issue
**Details**:
1. Sync data and find a furniture item with an unresolved issue on it
2. Furniture symbol showing with /!\ decoration - OK
2. Open the furniture form, Issue is listed at the bottom of the form
3. Open the issue from the furniture form, change the status to Resolved, save the form
4. Return to map, furniture map icon now doesn't have the /!\ triangle on it - OK
5. Re-open the furniture form, the issue is still listed, can open the issue details - OK
6. Save or Cancel the issue form - map icon shows without /!\ decoration - OK
7. Sync data but don't process it yet
8. Check the map, furniture map icon now doesn't have the /!\ triangle on it - OK
9. Open the furniture form, the issue is still listed - (this contradicts comment by LS above)
10. Process data into CAMS and sync mobile app again
11. Check the map, furniture map icon now doesn't have the /!\ triangle on it - OK
12. Open the furniture form, the issue is still listed - See #76 

happy that this specific issue is OK, but some problems remain, recorded under #76

**Comment by Timothy-D** [comment] 2020-12-15 14:36
Unable to test this in 4.4.12 as unable to access existing issues on furniture - see #76

**Comment by Timothy-D** [comment] 2020-12-18 15:43
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**:
**Sync Account**:
**Status**:
**Details**:

1. Sync data and find a furniture item with an unresolved issue on it
2. Furniture symbol showing with /!\ decoration - OK
3. Open the furniture form, Issue is listed at the bottom of the form
4. Open the issue from the furniture form, change the status to Resolved, save the form
5. Return to map, furniture map icon now doesn't have the /!\ triangle on it - OK
6. Re-open the furniture form, the issue is still listed, can open the issue details - OK
7. Save or Cancel the issue form - map icon shows without /!\ decoration - OK
8. Sync data but don't process it yet
9. Check the map, furniture map icon now doesn't have the /!\ triangle on it - OK
10. Open the furniture form, the issue is still listed as resolved- OK
11. Process data in CAMS
12. Sync tablet
13. Furniture map icon doesn't have the /!\ triangle on it - OK
14. Check Furniture form, issue is not shown - OK

**Closed** 2021-04-30 10:34 UTC
Labels: Time <0.5day
